// =====================================================================
// Référentiel des clubs (base FFF) — source centralisée des listes
// déroulantes "club" de l'application.
// ⚠️ Mise à jour annuelle prévue au 1er juillet de chaque année.
// =====================================================================

export const CLUBS = [
  "Paris Saint-Germain (PSG)",
  "Olympique Lyonnais (OL)",
  "Olympique de Marseille (OM)",
  "AS Monaco",
  "LOSC Lille",
  "Stade Rennais FC",
  "OGC Nice",
  "RC Lens",
  "RC Strasbourg",
  "Montpellier HSC",
  "Toulouse FC",
  "AJ Auxerre",
  "AS Saint-Étienne",
  "Stade de Reims",
  "FC Nantes",
  "Le Havre AC",
  "Angers SCO",
  "Brest (Stade Brestois)",
  "FC Lorient",
  "SM Caen",
  "Amiens SC",
  "ESTAC Troyes",
  "FC Metz",
  "EA Guingamp",
  "Paris FC",
  "SC Bastia",
  "Red Star FC",
  "Valenciennes FC",
  "FC Sochaux-Montbéliard",
  "FC Versailles 78",
  "Dijon FCO",
  "US Concarneau",
  "Bourg-en-Bresse",
  "AS Saint-Priest",
  "Racing Club de France",
  "CS Brétigny Football",
  "JA Drancy",
  "US Torcy PVM",
  "FC Montfermeil",
  "AS Béziers",
  "AAS Sarcelles",
  "FC Montrouge 92",
  "ES Nanterre",
  "Cavigal Nice",
  "ASPTT Marseille",
  "Istres FC",
  "FC Lyon 1893",
  "Lyon - La Duchère",
  "US Orléans",
  "Chamois Niortais",
  "US Avranches",
  "Sablé FC",
  "La Roche VF",
  "FC Mantois 78",
  "CS Mainvilliers",
  "AC Cambrai",
  "Canet RFC",
  "ESC Montferrier",
  "FC Borgo",
  "Gazélec FC Ajaccio",
  "Jeunesse Villenavaise",
  "FC Marmande 47",
  "Quevilly-Rouen (QRM)",
  "Racing Besançon",
  "Paris 13 Atletico",
  "AS Beauvais Oise",
  "US Boulogne CO",
  "Vannes OC",
  "Stade Bordelais",
];
